# Generated by Django 3.0 on 2019-12-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191221_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
