# Generated by Django 3.0.3 on 2020-03-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_lastmessageread_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('send_private_message', 'Send Private Message')]},
        ),
    ]
