# Generated by Django 3.0 on 2019-12-20 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('energie', models.CharField(max_length=15)),
                ('mileage', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=100)),
                ('car_picture', models.ImageField(upload_to='car_picture')),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
