# Generated by Django 3.0.3 on 2020-02-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createdeal',
            old_name='energie',
            new_name='fuel',
        ),
    ]
