# Generated by Django 3.0.3 on 2020-02-25 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservationdeal_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservationdeal',
            name='reserved_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
