# Generated by Django 3.0.3 on 2020-02-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200225_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createdeal',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='createdeal',
            name='mileage',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='createdeal',
            name='price',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
