# Generated by Django 3.0.3 on 2020-02-29 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0008_auto_20200225_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdeal',
            old_name='user',
            new_name='user_reserve',
        ),
        migrations.AddField(
            model_name='reservationdeal',
            name='user_owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
