# Generated by Django 3.0.3 on 2020-02-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20200229_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdeal',
            name='request',
            field=models.BooleanField(default=True),
        ),
    ]
