# Generated by Django 3.0.3 on 2020-02-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_reservationdeal_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationdeal',
            old_name='request',
            new_name='requested',
        ),
        migrations.AddField(
            model_name='reservationdeal',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
